---
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ancestral Graphs example with Stop-signal data
*Sara Jahfari April 2017*

Before running through the example bellow get an intuition for the method and stats reading Lourens Waldorp's 2011 NI paper [here](http://www.sciencedirect.com/science/article/pii/S1053811910013479).

1. Getting started
----------------------
Ancestral Graphs relies on a number of packages such as graphs, RBGL and ggm. These packages are updated in a fast rate, and for now you will have to run an older version of R (version 3.0.2) in order to use the validated versions of these packages for AG. You can find the checked package versions in the folder AG_codes/Rpackage_checked. 

For me it works really well to use [RSwich](https://support.rstudio.com/hc/en-us/articles/200486138-Using-Different-Versions-of-R) to swich between the newest version of R and this older version for AG. After installing the older version of R, and using RSwich make sure that you are running R version 3.0.2 (2013-09-25).   

For an elaborate workflow please read the *AG_Readme.pdf*. All of these steps are also in the *EvaluateStop_example.R*. If you have questions let me know. Have fun!


